### ISSUE TITLE
No way to select "Inverter only" or "Charger only" options from Inverter / Charger mode setting

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1040]
[Reported](https://community.victronenergy.com/questions/279997/venus-os-v3408-available-for-testing.html?childToView=283848#answer-283848) by Kevin. "gui-v2 dialog that selects inverter mode is showing Charger only and Inverter only grayed out and not selectable. The only selections permitted are off and on. My system uses a Multi Compact 120v unit. All 4 selections are shown and function in gui-v1 and also in GuiMods. Tested this without any third party mods just to be sure there is no interaction."

Looking at the  Inverter / Charger mode dialog code the items "Inverter only" or "Charger only" should be enabled if isMulti parameter is true, but the parameter is never defined.

**Comment by kwindrem** [comment]
That explains the problem. Thanks.

An inverter/charger (Multi/Quattro) would have charger only and inverter only modes. Inverter only (eg Phoenix) which still can be VE.Bus would have only on and off. isMulti is true if the VE.Bus device has any AC inputs.

gui-v1 does gray out these selections however I would think invalid selections should not be shown rather than grayed out. 

Note also, VE.Direct inverters also have an ECO mode selection in addition to on and off. Handled in PageInverter.qml for gui-v1
