### ISSUE TITLE
PageSettingsHub4 should have a 'Dynamic ESS' item

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1101]
See gui-v1 PageSettingsHub4.qml, PageSettingsDynamicEss.qml

**Comment by blammit** [comment]
Fixed by https://github.com/victronenergy/gui-v2/pull/1155

**Comment by chriadam** [comment]
As per testing on Tuesday:
1) If "Grid Metering" is not "External meter" then the Peak Shaving "Limit system AC import current" should have a popup saying why it cannot be enabled (i.e. because "Grid metering" is not set to "External meter").
2) "Scheduled charging" should be "Scheduled charge levels" and it should have a summary text in the list item "Inactive" if none exist.

(Question: after one schedule is enabled but not active, should the test read "Scheduled" rather than "Inactive"?)

**Comment by blammit** [comment]
> If "Grid Metering" is not "External meter" then the Peak Shaving "Limit system AC import current" should have a popup saying why it cannot be enabled (i.e. because "Grid metering" is not set to "External meter").

@ReinvdZee instead of showing this popup, I've added this information below the switch when the switch is disabled. I think this provides the information more effectively as you don't have to click it in order to see the popup message and understand why it's disabled. Is this okay?

![image](https://github.com/victronenergy/gui-v2/assets/1260099/91a6d9e0-a1c1-4fb1-adff-3fa1dbd43627)

**Comment by ReinvdZee** [comment]
@blammit, 

> @ReinvdZee instead of showing this popup, I've added this information below the switch when the switch is disabled. I think this provides the information more effectively as you don't have to click it in order to see the popup message and understand why it's disabled. Is this okay?

I agree, looking good!

**Comment by blammit** [comment]
Changes have been merged; closing.

**Comment by DanielMcInnes** [comment]
verified with Rein
