### ISSUE TITLE
Numbers are inconsistently formatted in non-en locales

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1108]
gui-v2 should format numbers consistently in non-en locales.

For example, in Chrome if you set the "Preferred language" to German, then when running gui-v2 in wasm, then the Brief and Overview pages show quantities with the '.' period as a decimal separator:

![image](https://github.com/victronenergy/gui-v2/assets/1260099/c9f9ae12-8611-47bb-8df5-978922ecb55e)

However, when opening an Inverter/Charger control card, the current limit spinbox uses a comma (`,`) as the decimal separator:

<img width="871" alt="image" src="https://github.com/victronenergy/gui-v2/assets/1260099/acfec6db-820d-4e67-bf30-e8903f39c0bd">

gui-v2 should just use one or the other instead of mixing them. Presumably it should always respect the formatting for the system locale.

**Comment by blammit** [comment]
This is causing a bug in the "Minimum and maximum gauge range settings" as reported in https://github.com/victronenergy/gui-v2/pull/1043#issuecomment-2114044833. In that issue, if the locale is de_DE, the page shows the number with a period as a decimal separator, but requires that the input uses a comma as a decimal separator.

**Comment by blammit** [comment]
Part of the problem is that in wasm, there are multiple locale settings:

- the locale set within gui-v2 based on the language settings
- the default locale, as set by the browser

If these differ, then gui-v2 needs to pick one of these and follow it consistently.

**Comment by mr-manuel** [comment]
I tested this build and it seems that it gets the locale of the browser and not of the language setting of Venus OS.

This build:
![Bildschirmfoto am 2024-05-22 um 06 42 01](https://github.com/victronenergy/gui-v2/assets/12592765/b890cb48-dda4-4c42-9580-08e141b845b2)

Main branch:
![Bildschirmfoto am 2024-05-22 um 06 42 49](https://github.com/victronenergy/gui-v2/assets/12592765/560a3ab7-9a7c-4e1b-a10a-ae04597ce7fa)

Additionally there is still a strange behaviour:
![venus-os](https://github.com/victronenergy/gui-v2/assets/12592765/48cafa03-c715-4fd9-bcda-717b8d73f947)

**Comment by mr-manuel** [comment]
Now it looks good!

## Venus OS in German
![Bildschirmfoto am 2024-05-22 um 11 36 32](https://github.com/victronenergy/gui-v2/assets/12592765/a37a503d-a059-440b-b37b-8b5e9af9c310)
![Bildschirmfoto am 2024-05-22 um 11 42 07](https://github.com/victronenergy/gui-v2/assets/12592765/862ed6eb-0448-44ea-b9ba-81e806600d04)

## Venus OS in English
![Bildschirmfoto am 2024-05-22 um 11 42 44](https://github.com/victronenergy/gui-v2/assets/12592765/e675021b-2544-4d4c-aab0-f159102ce45a)
![Bildschirmfoto am 2024-05-22 um 11 42 27](https://github.com/victronenergy/gui-v2/assets/12592765/1ee846db-8ed1-404a-a9df-63776aaa4a95)

Remains only the issue, if you enter `.` instead of `,` (or vice versa, depending on the language) you get an odd answer. I don't know, if you want to fix that also. If yes, I don't see it that critical for `v1.0.0` release.

**Comment by blammit** [comment]
> Remains only the issue, if you enter . instead of , (or vice versa, depending on the language) you get an odd answer. I don't know, if you want to fix that also. If yes, I don't see it that critical for v1.0.0 release.

Thanks for verifying! Yes, this issue does remain, but we will leave it for now.

**Comment by blammit** [comment]
Note: the resolution here was to always use the C locale to format numbers, as users may prefer the dot as a decimal separator, regardless of the application locale.
