### ISSUE TITLE
Levels page fails to display correct tank names

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1258]
Customer is [reporting](https://community.victronenergy.com/questions/292058/venus-os-v34026-available-for-testing.html?childToView=297192#answer-297192) that the Levels page fails to display tank names: "One small thing… running -29, I am using a Garnet Seelevel 709 RV-C for my tanks levels. In the level screen, the name are all the same for all tank, but the pictogram are good. Note that the propane tank is connected directly to the Cerbo. Also, I have no black tank but it is still showing."

![image](https://github.com/victronenergy/gui-v2/assets/2203667/9dc30d5b-6d82-4529-b110-7f7e236bd646)

Brief page and Devices list display correct names.

![image](https://github.com/victronenergy/gui-v2/assets/2203667/ea810322-aab4-4d4c-ab27-a81830c0adb3)
![image](https://github.com/victronenergy/gui-v2/assets/2203667/e2dce9ff-5dc4-4be5-90fb-1cf91f7db67e)

**Comment by blammit** [comment]
Can repro with Boat/Motorhome 1 demo.

**Comment by blammit** [comment]
Actually, what's happening here is that gui-v2 is showing the device "Product Name" as expected:

- Brief page: shows the tank type (e.g. "Fresh water")
- Device List: shows the tank type and device instance (e.g. "Fresh water (62)")
- Tank gauges (where this bug is reported): shows the tank `/CustomName`, or if that doesn't exist, the `/ProductName`

Here, because the first three tanks are from tank sensors, they don't have individual names: they do not have `/CustomName` values, and the `/ProductName` for all of them is "Tank sensor".

**Comment by blammit** [comment]
> Also, I have no black tank but it is still showing.

Not sure what we can do about this one -- the tank must be still appearing under `com.victronenergy.tank.*` as a valid tank, if it is able to appear as a Black Water tank.
