### ISSUE TITLE
The grid widget displays the wrong value for total power

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1261]
This can usually be reproduced at 'GRN - RS 3phase without EM'.

![Screenshot from 2024-06-20 11-11-56](https://github.com/victronenergy/gui-v2/assets/6416318/62b33b62-562f-4cd4-b3ce-60a07ee77543)

In gui-v1, the total power displayed on the grid widget (in this case, 84W) is always the sum of the 3 phases. In gui-v2, we seem to display 3x whatever the greatest single phase is (in this case, we display 3 x 99W = 297W). This becomes particularly obvious when a 3 phase is only importing power on a single phase.

![Screenshot from 2024-06-20 11-11-48](https://github.com/victronenergy/gui-v2/assets/6416318/5f1914e5-158a-48b9-9ec1-03ba6cb41532)

**Comment by blammit** [comment]
I think this bug is specific to AC inputs on Multi RS systems.

**Comment by blammit** [comment]
Are the missing L2 and L3 values due to https://github.com/victronenergy/gui-v2/issues/1144?

That is, we're seeing

![image](https://github.com/victronenergy/gui-v2/assets/1260099/87deb0aa-2faf-4e1f-9815-beb74b3bdd22)

instead of

![image](https://github.com/victronenergy/gui-v2/assets/1260099/86334fde-7e98-4dbd-a4c5-5a20ee9127d9)

**Comment by DanielMcInnes** [comment]
No, it's an unrelated issue. I originally fixed it on that branch, but decided it should be in a separate issue.

**Comment by blammit** [comment]
Okay, is there a task for that one?

**Comment by DanielMcInnes** [comment]
Here you go https://github.com/victronenergy/gui-v2/pull/1263
