### ISSUE TITLE
Display individual Lynx Smart BMSs in the device list

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1319]
Gui-v2 only displays the totals for Lynx Smart BMS. Gui-v1 displays the individual BMSes as well.

![image](https://github.com/user-attachments/assets/4a4f6db7-0b6d-457a-ac84-ba203a9a5b3b)
![image](https://github.com/user-attachments/assets/5ce46bd9-467f-4597-a444-6f45f166f464)

**Comment by blammit** [comment]
Screenshots are for [this](https://vrm.victronenergy.com/installation/323213/overview ) installation.

**Comment by blammit** [comment]
On [the installation](https://vrm.victronenergy.com/installation/323213/overview), gui-v2 has four battery services under `com.victronenergy.battery.*`, as follows:

![image](https://github.com/user-attachments/assets/faaebb4a-f14b-4864-ad2e-bea5c6beb8cc)

The second one ("lynxparallelundefined") is probably a bug that can be ignored. The problem is that only the `com.victronenergy.battery.lynxparallel2` service appears in MQTT under `mqtt/battery/*`; the `com.victronenergy.battery.socketcan_can0_*` services do not, so they are not accessible by gui-v2 on wasm.

@ReinvdZee  would you know why this is happening? Is there something special about those battery services? I found that [this installation](https://vrm.victronenergy.com/installation/402872/overview) has similar `com.victronenergy.battery.socketcan_can0_*` services, but they are accessible under `mqtt/battery/*` as expected so they do appear in gui-v2 on wasm, so I'm not sure what's happening here.

**Comment by blammit** [comment]
@DanielMcInnes mentioned the installation is playing a replay, so perhaps that's the issue?

**Comment by DanielMcInnes** [comment]
Closing issue, this has been fixed somewhere else, individual Lynx smart BMSes are now displayed individually

![Screenshot from 2024-08-20 11-09-22](https://github.com/user-attachments/assets/d206395f-7037-4848-afc6-0f8635e889e8)
