### ISSUE TITLE
Move Qt used for WASM builds from 6.6.2 to 6.6.3

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1359]
as discussed in todays dev meeting.

we're also doing the same for Qt in Venus OS: https://github.com/victronenergy/venus/issues/1323

**Comment by chriadam** [comment]
Task should require just:
1) update QT_VERSION in build-wasm.yml to 6.6.3, see https://github.com/victronenergy/gui-v2/blob/main/.github/workflows/build-wasm.yml#L11 
2) update the docs in https://github.com/victronenergy/gui-v2/wiki/How-to-build-venus-gui-v2#building-for-webassembly to say 6.6.3 instead of 6.6.1 etc.

**Comment by DanielMcInnes** [comment]
@chriadam do we want to change CMakeLists.txt to use Qt6.6.3 as well, so that we're running the same wasm builds that goes into cerbos?
