### ISSUE TITLE
Adjust Settings list bounds behaviour

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#1363]
Currently, you can elastic scroll above the list.  It would be better to set StopAtBounds behaviour.
The elastic scrolling can, in worst case, cause delegates to go out of view and be destroyed (then recreated on rebound), which is bad.

**Comment by blammit** [comment]
One small problem with this: in Settings > General, it is deliberately possible to drag the list beyond the bounds, so that if you hold for 5 seconds, it changes the access level. 

To preserve this feature, I will keep this drag-beyond-bounds behaviour just for this page. We can change this later if needed.
