### ISSUE TITLE
Ask for confirmation when setting VRM mode to 'off' or 'read-only' when doing that over VRM

### ISSUE THREAD

**Issue by wiebeytec** [victronenergy/gui-v2#1378]
This applies to the setting Settings -> VRM Portal -> VRM Mode. 

Implement a popup that says "Are you sure? Changing this setting to read-only or off will lock you out. Please type YES to confirm".

And then have a box where people can type YES. Note that if that is more difficult than whats possible to do in a day; then skip that for now and leave the issue open to do that later.

Preferably the popup is only shown when gui-v2 is in WASM mode and opened via VRM. As far as I know, gui-v2 code knows that (?), and can only show the popup in that situation. Same thing: if more difficult, then fine to do that only later.

Background: when you use GUIv2 over VRM, it's currently very easy to (semi) lock yourself out by changing the new VRM mode to 'off' or 'read-only'. Immediately after setting either mode, it will stop accepting new commands.

**Comment by blammit** [comment]
It is difficult to show a text field in a popup at the moment, due to issues with the popup overlay and VKB placement, as described here: https://github.com/victronenergy/gui-v2/issues/1104

However, we can show a confirmation popup like this:

<img width="961" alt="image" src="https://github.com/user-attachments/assets/90695a71-e837-4437-b9cf-da8362345679">

I have implemented this popup solution here: https://github.com/victronenergy/gui-v2/pull/1381
