### ISSUE TITLE
Changing VRM device instances does not work

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1391]
On Venus OS v3.50~13. Changing VRM device instances does not work as expected. 
I can change the VRM instance number and a reboot dialog shows up when leaving the menu. However, after rebooting, the VRM instance has not changed. I tried changing the SmartShunt VRM ID from 279 to 280, but the ID remains 279 after the reboot.

![image](https://github.com/user-attachments/assets/971ece96-58a2-4c84-8154-51f7fe3358b3)

And it also lists a lot of unconnected devices. I don't think it's supposed to do that? 
I also noticed that the reboot dialog shows after editing a field and then editing it back to the original value. In this case, no ID's have changed, so returning to main menu should not invoke the reboot dialog.
![image](https://github.com/user-attachments/assets/fc372962-9e6c-41c9-ba3c-63a0cc887bb6)

@blammit, @chriadam @DanielMcInnes
Can you take a look? Its a bit urgent.
You can use [this system](https://vrm.victronenergy.com/installation/323213/overview) to test which has a smartshunt connected.

**Comment by ReinvdZee** [comment]
Setting the deviceinstance manually with dbus-spy works: 
![image](https://github.com/user-attachments/assets/af70e700-7c64-4a96-ad61-f28e9d7f6f79)
After the reboot, the smartshunt also shows up in VRM with the new deviceinstance.

**Comment by blammit** [comment]
Sure, will look into this.

**Comment by blammit** [comment]
@ReinvdZee I have a tentative fix for this, and will have a PR ready tomorrow. Regarding this point:

> And it also lists a lot of unconnected devices. I don't think it's supposed to do that?

The list shows all items under `com.victronenergy.settings/Settings/Devices` that have a valid `com.victronenergy.settings/Settings/Devices/ClassAndVrmInstance` value. If no /CustomName or /ProductName is available then it shows "Unconnected". This was discussed when the issue was created in https://github.com/victronenergy/gui-v2/issues/305 but perhaps there's a better way to do this now? It would certainly be nicer to find a better display name.

**Comment by ReinvdZee** [comment]
@blammit 

Good that you have a fix already. Regarding the unconnected devices being displayed, this is not urgent and I don't really have a better way for now.

**Comment by blammit** [comment]
https://github.com/victronenergy/gui-v2/pull/1395 should resolve this issue.

I found some sorting issues in the list while testing; have filed https://github.com/victronenergy/gui-v2/issues/1396 for that.
