### ISSUE TITLE
Double check that inverter warnings cause notification be triggered

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#1439]
This discussion was triggered by https://victron.discourse.group/t/3-50-13-gui-v2-low-battery-warnings-not-signaled/521
Which is slightly different, as it's about LED indications of low battery.
But Matthijs wants to double check that inverter warnings to indeed trigger notification page.

**Comment by vejpasop** [comment]
The difference between GUI V1 and V2 is mostly the low battery led indication in the Multi

On GUI V1 in case of a low battery **warning** you will see the low batter led flashing on GUI. 
![image](https://github.com/user-attachments/assets/1c592080-5f13-49a6-aeb4-394d537d222c)

Since it is an warning the GUI will not jump to notifications. It will not jump to the notification screen. Both GUI V1 and V2 will only do that in case of an **alarm**

**Comment by vejpasop** [comment]
On GUI V2, when there is an alarm the user interface jumps to the Notification screen and the backlight comes on. Also when the alarm is cleared the backlight comes on. On a warning the backlight does not come on and the user interface does not jump to the notification screen. You will not be informed about the warning unless you touch the screen.
Example: 
Screen1,low battery warning active 
![image](https://github.com/user-attachments/assets/f592f89d-5c21-443a-964e-867c4074f78d)

Screen 2. when you touch the screen the red dot on the Notifications page selector only hints about the warning
![image](https://github.com/user-attachments/assets/312c7a96-aab3-4789-857f-d606b5a56d08)

**Comment by vejpasop** [comment]
Note. When Matthijs was testing on my Ekrano he needed to touch the "Acknowledge alerts" button in the notification screen twice in order to make it respond. He could reproduce it. However when I try I can't reproduce it on the same Ekrano.

**Comment by chriadam** [comment]
Thank you for testing!  Created #1455 to track that latter issue.  Closing this issue, as it seems that according to the testing it works as required.  Please reopen if I am mistaken.
