### ISSUE TITLE
10.g MQTT: Handle connection failure in gui-v2

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#214]

**Comment by chriadam** [comment]
We merged https://github.com/victronenergy/gui-v2/pull/585 which fixes it.
Obviously, the fix isn't perfect because QtMqtt can be slow telling clients that they've disconnected, so it can take some time for us to react to the disconnection.  But the disconnection IS eventually noticed and handled properly, now.

Closing task.  Can reopen if there is some specific issue.
