### ISSUE TITLE
Check which parts of gui-v1 main.qml need to be ported

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#264]
https://github.com/victronenergy/gui/blob/master/qml/main.qml from gui-v1 contains a number of features that have not yet been ported to gui-v1. Check what needs to be ported.

For example:

This changes the top application page to the firmware update (offline) page when a particular VRM storage error occurs:
```
   Connections {
                target: storageEvents
                onVrmStorageError: {
                        if (error === 4) {
                                setTopPage(offlineFwUpdates)
                        }
                }
        }
```

This shows a notification when touch input is disabled:
```
        Connections {
                target: vePlatform
                onMouseRejected: toast.createToast(qsTr("Touch input disabled"), 1000)
        }
```

This ensures the application shows various notifications when certain dbus signals are detected (e.g. for storage errors):
```
SignalToaster {}
```

**Comment by chriadam** [comment]
I don't think we should blindly copy random functionality from gui-v1 to gui-v2 unless explicitly requested to do so.
If there is some specific functionality missing from gui-v2, which is definitely wanted, a task/issue specific for that should be created so that we can track it properly.

Closing this task.
