### ISSUE TITLE
Bug: Some RuuviTag temps are missing from the Environment page - intermittent

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/gui-v2#511]
I have 5 temperature sensors in my system.
One is connected to a Cerbo analog input and appears on the Environment page.
The remaining 4 are RuuviTag bluetooth sensors. Only two of these appear in gui-v2 but all are visible in the original GUI with GuiMods installed.

There is not yet a I/O / Bluetooth menu in gui-v2 nor are any devices listed anywhere like the Device List menu in the original GUI but all 4 RuuviTag sensors appear in dbus-spy.

As I am writing this with the environment page open, one of the sensors appears for a while then disappears again. The 4th sensor does not ever seem to appear.

The only parameter that is changing is /Status. The sensor is visible when the /Status is 0 and not visible when /Status is 5 which is not documented in the dbus Wiki. Looking at the code status must be 0 in order to display the device.

It also may be that the /SeqNo is not updating as rapidly for the sensors that are not appearing compared to those that are there all the time.
If I use dbus-spy to disable the sensor that never appears, then reenable it, it shows up for about 5-6 seconds then disappears. Maybe the driver has a timeout that is too short?

If this is the wrong place to submit bugs, let me know where the right place is and I'll move things there.

**Comment by dirkjanfaber** [comment]
The bluetooth devices will be removed from the dbus after not receiving data for [120 seconds](https://github.com/victronenergy/dbus-ble-sensors/blob/master/src/ble-dbus.c#L422). At least that is how I interpret that code.

@blammit: Instead of looking at `/Status`, looking at `/Connected` is probably better for the bluetooth devices. 

And @kwindrem is right that the `/Status` not being zero indicates that there is something wrong with the device. Currently we have [the following statuses in gui-v1](https://github.com/victronenergy/gui/blob/master/qml/PageTemperatureSensor.qml#L62-L67):

| Code | Status |
| --- | --- |
| 0 | Ok |
| 1 | Disconnected |
| 2 | Short circuited |
| 3 | Reverse polarity |
| 4 | Unkown |
| 5 | Sensor battery low |

The most common numbers will be `0` and `5`. I suggest showing an icon of a depleting battery on its environment page, next to the readings.

**Comment by mpvader** [comment]
Stepping a bit back: why not always show them as long as they are on D-Bus? I don't see why there would need to be code to check anything at all.

Doing that would really be something unique, and making the whole thing more complicated and different.

@blammit wrote:

> We had an issue where the sensors were appearing even when they were offline, hence the /Status check.

Can you elaborate / point me to an explanation of more on that issue?

**Comment by blammit** [comment]
> Bea, can you elaborate / point me to an explanation of more on that issue?

I thought it was reported in #venus-tests (seeing temperature sensors that are offline) but I can't find that anymore unfortunately. But if it makes more sense to ignore that /Status check, I will remove it. I guess as long as it is connected, it could be shown anyway. Done here: https://github.com/victronenergy/gui-v2/pull/658

**Comment by mpvader** [comment]
> I guess as long as it is connected, it could be shown anyway.

slightly reworded: as long as its on D-Bus, it should be shown.

**Comment by mpvader** [comment]
Hey @blammit , this issue can be closed now that the PR is merged, right?

How is your normal flow by the way wrt issues and PRs?  Do you manually close the issues once they make it into a release? or?

**Comment by blammit** [comment]
Oops yes, closing. I normally add the issue to the PR so that it will close automatically. 

In the past I also added the issue numbers to the commits, but it started to become annoying when the issue log became clogged with updates every time the PR was updated.
