### ISSUE TITLE
Generator tile in overview not updating with generator status changes

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/gui-v2#518]
The Generator tile is not updating the generator running/stopped state or the running time properly. Also at times, the tile remains on Grid/Shore even though the system AC input type is changed to generator.

The state displayed here should also include warm-up, cool-down and post-cool-down periods especially beause the AC input is ignored in these states. This leaves the user to wonder why if the generator is running it is not being used.

**Comment by blammit** [comment]
> The Generator tile is not updating the generator running/stopped state or the running time properly. 

With https://github.com/victronenergy/gui-v2/pull/623, the Generator tile will only show a "stopped" status when stopped (and otherwise will just show the power input). When running, the detailed reason will be shown in the Generator "card" (shown when clicking the top-left buttons). The PR also adds the warm up / cooling down statuses.

>  Also at times, the tile remains on Grid/Shore even though the system AC input type is changed to generator.

This should be fixed by https://github.com/victronenergy/gui-v2/pull/609, but would be good to know if this is not the case.
