### ISSUE TITLE
Add warning for the gui-v2 selection

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/gui-v2#522]
Currently, the selector to activate gui-v2 says"(Check the beta announcement first)".

Since activating gui-v2 breaks VRM and that may be the only access to the GX device, it  may be worth adding a text box warning about that, in the UI version menu:

Warning:
Selecting Beta version (aka gui-v2) will disable the VRM Remote Console.
You will need local LAN access or a local display to return to the Standard version.

**Comment by chriadam** [comment]
Could you remind me: why does enabling gui-v2 disable VRM remote console?

**Comment by kwindrem** [comment]
Because running gui-v2 shuts down gui-v1 and the remote console uses gui-v1. I have experimented with running BOTH gui-v1 and gui-v2 and it works so maybe this is a solution for now.

Obviously, gui-v1 and gui-v2 can't both run on the local display at the same time, so what I did was run gui-v1 in headless mode. That provided the VRM remote console something to connect to.

**Comment by chriadam** [comment]
https://github.com/victronenergy/gui-v2/pull/969 adds a warning dialog, but one part of the change might cause issues which still need to be resolved.

Out of interest, is v1 of gui expected to be the service which provides VRM Remote Console support into the future?  If so, maybe when we switch to gui-v2, we should enable headless mode on gui-v1 as part of that setting change?  Or am I misunderstanding?

**Comment by chriadam** [comment]
Actually, after some discussion with Matthijs: changing the setting via gui-v2 launched by VRM is fine, because gui-v2 launched by VRM will continue to work regardless of whether you change this setting.  (The setting which breaks gui-v2 over VRM is the "VRM two-way communication" setting, but that one is tracked by #967).  So my PR should not be necessary.

The warning you mention is probably needed in the v1 of the gui, for the remote console case, and not in gui-v2.

Closing issue.
