### ISSUE TITLE
Overview Page: Battery connection line is not animated

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#567]
The battery connection line on the overview page is not animated. I tried with v0.1.20 and the latest main build.

![guiv2_bubbles](https://github.com/victronenergy/gui-v2/assets/12592765/b6481f3d-ca2c-4800-b3ac-32da8fd31a83)

**Comment by chriadam** [comment]
@blammit if I remember correctly you spoke to jperez about this / the flow state is defined by some systemcalc value?

**Comment by mr-manuel** [comment]
There is a threshold that has to be reached, that the flow is shown. I think it was 30 W.

**Comment by blammit** [comment]
@mr-manuel  Is this regarding the flow between the Inverter/Charger and the Battery? I just checked and the animation seems to be working, so maybe something else is going wrong here. That is defined by whether the /Dc/0/Power of the main VE.Bus service (as defined by `com.victronenergy.system/VebusService`) is over 30 (or under 30). Could you check that value?

Also if this is being tested via wasm, there are some fixes currently underway involving the MQTT connection and data fetching, so that could also be a factor.

**Comment by mr-manuel** [comment]
@blammit yes amd yes, it's the wasm build. I will try the latest main build or the branch, if I find one.

**Comment by chriadam** [comment]
No MQTT fixes are available yet, I was initially hoping to have a PR up tonight but it looks like it won't be ready until tomorrow night.

**Comment by mr-manuel** [comment]
No problem

**Comment by chriadam** [comment]
This is still problematic and needs to be fixed.  Marking as medium_prio and giving 1.0.0 tag.

**Comment by DanielMcInnes** [comment]
still an issue
![Screenshot from 2024-01-31 16-02-11](https://github.com/victronenergy/gui-v2/assets/6416318/986ea180-a031-4102-be20-2da0dde38cd1)
