### ISSUE TITLE
Allow developers to disable qmlcachegen for faster builds

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#577]

**Comment by chriadam** [comment]
As noted in the PR comment, disabling qmlcachegen also reduces the binary size (since otherwise the pre-generated type data cache is embedded into the executable as a resource).  This means that disabling qmlcachegen results in approx 4MB size reduction for WebAssembly blob (at the cost of slower runtime performance, due to requiring run-time compilation of QML types).  Given that we (try to) compile all QML types during the splash loading screen, the question effectively becomes: what takes longer: compiling all types at runtime, OR downloading 4MB (closer to 1 MB after gzipping).

Benchmarking would be needed to say for sure, but my gut instinct is that compiling all types at runtime probably takes longer, for most clients with good broadband connections.  However, that compilation time is also somewhat parallelised with other splash screen operations (i.e. waiting for all initial MQTT messages to be received from the broker).
