### ISSUE TITLE
gui-v2 crashed when opening generator device

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#687]
Reported here: https://community.victronenergy.com/questions/257253/venus-os-v32040-available-for-testing.html?childToView=259058#comment-259058

https://www.youtube.com/watch?v=GW9gaJ5qhSg

**Comment by blammit** [comment]
I think this is related to a VeQuickItem uid being invalid when the page is initially loaded, which should be fixed by 28b03d2888933ad0580f7828871c354729c516b0 and other recent veutil changes. However, it would be nice to test this on a real system if I knew the installation or configuration -- I haven't been able to reproduce the crash when trying some of the venus-docker simulations.

**Comment by chriadam** [comment]
It would have only crashed with dbus backend since the Utils.normalizedSource() method (which I've removed in that change you mentioned) only stripped the dbus path prefix.  So trying to repro with a remote installation would never have triggered the issue.

I reproed on cerbogx and fixed.

**Comment by chriadam** [comment]
High prio.

**Comment by chriadam** [comment]
Can we get some more information about the product, e.g. the product id?
I assume the InteliLite is a type of generator / genset device?
Is it a Fischer Panda device, or something else?

Certainly, my PR should have resolved the crash due to any sort of transient invalid UID state, but I would like to be able to trace the specific codepath taken for this device - for which I need the product id etc.

**Comment by mpvader** [comment]
Yes an Intelilite is a model generator start/stop controllers, its from Comap. Setting up a bench test for that is not so easy, I've asked the user that reported this to confirm that its now fixed.

For me its fine if you close meanwhile this issue; it will come back if there is still an issue.



![image](https://github.com/victronenergy/gui-v2/assets/5200296/927f2696-1319-4e68-bbc1-72c9541e91dc)

**Comment by mpvader** [comment]
Just got the confirmation, fixed indeed @chriadam
