### ISSUE TITLE
Support tanks without "capacity" and "remaining" values

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#746]
Some tanks may not have values for both the "capacity" and "remaining" values. 

If this is the case:

- the "level" value should be used to calculate the displayed level in the Tanks tab, instead of trying to calculate it from the capacity/remaining
- hide the capacity/remaining text below the gauge so that it doesn't show "0.000/0.000m3" or such.

**Comment by DanielMcInnes** [comment]
martin
  12 days ago
@Bea Lam
 Is it a known issue that the % is not properly calculated for tanks that are grouped together?
Has been reported by a tank sensor integration partner. Their tank senders don't have a capacity set and thus no absolute level.
![image](https://github.com/victronenergy/gui-v2/assets/6416318/fea9dc77-c554-4321-a070-6f0ef2d24bec)

martin
  12 days ago
On my system it looks like this in gui v1 and 2 (only one sensor properly connected)
![image](https://github.com/victronenergy/gui-v2/assets/6416318/bb0edf0c-d9c2-47d4-9e8a-a4d41a04e7db)

martin
  12 days ago
Remaining & Capacity topics are null
![image](https://github.com/victronenergy/gui-v2/assets/6416318/75985b1b-e4fa-437b-b1b2-866fc46378a0)

Bea Lam
  12 days ago
I didn’t realise that both remaining and capacity could be missing. Thanks, I’ve created https://github.com/victronenergy/gui-v2/issues/746 to fix this.
I guess in this case, the bottom label can be hidden, instead of showing some nonsense like 0.000/0.000m3.
Note that you might see some tank volume and unit conversion issues on older releases too, there were a bunch of tank fixes in the recent v3.30~3 release.
![image](https://github.com/victronenergy/gui-v2/assets/6416318/6293469f-93c2-4d02-a1dd-206f1b50fd71)

**Comment by DanielMcInnes** [comment]
Adding 'blocked' tag - I need the site with the issue to come online to test my changes.

**Comment by blammit** [comment]
Removing blocked tag, we could mimic the conditions locally for now.

**Comment by mpvader** [comment]
@martinbosma what brand or type tank senders is this about? can you give me some background to understand this one better?

**Comment by martinbosma** [comment]
Garnet, connected via RV-C.

**Comment by kwindrem** [comment]
In addition to SeeLevel RV-C not having capacity, both SeeLevel RV-C and N2K do not support custom names. This makes it difficult to differentiate tanks as displayed on the GX device. While SeeLevel RV-C and N2K don't support two identical tank types, Soul does. I would expect Soul to not report capacity or names as well because it uses RV-C.

I see no reason Venus OS can't add local /Capacity, /CustomName parameters and calculate /Remaining locally if the sensor system doesn't report them. If values are received from the sensor system they would simply overwrite any values set locally.

A discussion about this some time ago suggested that the "right" way is for the sensor to support these parameters so that all control systems show these senors receive the same information. That may be true but results in missing information which could easily be set on each control system once during system configuration.

**Comment by blammit** [comment]
Note that gui-v2 will calculate the equivalent /Capacity if the /Level and /Remaining are available, though perhaps this could be done at a lower level instead for convenience, to make it available elsewhere.
